---
- name: Gather facts and append to CSV
  hosts: all
  gather_facts: yes
  vars:
    csv_file: "/tmp/all_hosts_facts.csv"
    csv_header: "Inventory Host,Hostname,OS,IP,CPU Count,CPU Cores per CPU,Threads per Core,Memory(MB),Machine Type,Virtualization Type"

  tasks:

    - name: Ensure CSV file exists with header
      delegate_to: localhost
      lineinfile:
        path: "{{ csv_file }}"
        line: "{{ csv_header }}"
        create: yes
        insertafter: BOF
      run_once: true

    - name: Build CSV line for host
      set_fact:
        csv_line: >-
          "{{ inventory_hostname }},
          {{ ansible_facts.hostname }},
          {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }},
          {{ ansible_facts.default_ipv4.address | default('N/A') }},
          {{ ansible_facts.processor_count }},
          {{ ansible_facts.processor_cores }},
          {{ ansible_facts.processor_threads_per_core }},
          {{ ansible_facts.memory_mb.real.total }},
          {{ 'VM' if ansible_facts.virtualization_role == 'guest' else 'Physical' }},
          {{ ansible_facts.virtualization_type | default('None') }}"

    - name: Append host CSV line
      delegate_to: localhost
      lineinfile:
        path: "{{ csv_file }}"
        line: "{{ csv_line }}"
        create: yes
        insertafter: EOF

